import { Product } from "../models/Product";

const seedData = [
    {
        sku: "OLI-SW30-001",
        name: "Shell Helix Ultra 5W-30 1L",
        category: "pelumas",
        rating: 5,
        reviews: 24,
        price: 185000,
        originalPrice: 210000,
        badge: "Sale",
        stock: 50,
    },
    {
        sku: "FLT-OLI-002",
        name: "Bosch Filter Oli Premium",
        category: "filter",
        rating: 4,
        reviews: 18,
        price: 65000,
        originalPrice: null,
        badge: "New",
        stock: 80,
    },
    {
        sku: "SPK-IRD-003",
        name: "NGK Busi Iridium IX",
        category: "sparepart",
        rating: 5,
        reviews: 31,
        price: 125000,
        originalPrice: null,
        badge: null,
        stock: 60,
    },
    {
        sku: "AKI-GSA-004",
        name: "GS Astra MF 55B24L",
        category: "aki",
        rating: 4,
        reviews: 9,
        price: 750000,
        originalPrice: 820000,
        badge: "Sale",
        stock: 20,
    },
    {
        sku: "OLI-CTR-005",
        name: "Castrol GTX 20W-50 4L",
        category: "pelumas",
        rating: 4,
        reviews: 16,
        price: 195000,
        originalPrice: null,
        badge: null,
        stock: 45,
    },
    {
        sku: "FLT-AIR-006",
        name: "Mann Filter Udara C 2999",
        category: "filter",
        rating: 5,
        reviews: 12,
        price: 85000,
        originalPrice: 95000,
        badge: "Sale",
        stock: 70,
    },
    {
        sku: "SPR-TBK-007",
        name: "Gates Timing Belt Kit",
        category: "sparepart",
        rating: 5,
        reviews: 7,
        price: 285000,
        originalPrice: null,
        badge: "New",
        stock: 30,
    },
    {
        sku: "AKI-YTZ-008",
        name: "Yuasa YTZ14-S Motorbike",
        category: "aki",
        rating: 4,
        reviews: 5,
        price: 480000,
        originalPrice: null,
        badge: null,
        stock: 15,
    },
    {
        sku: "OLI-PRT-009",
        name: "Pertamina Fastron 10W-40",
        category: "pelumas",
        rating: 4,
        reviews: 41,
        price: 120000,
        originalPrice: null,
        badge: "Hot",
        stock: 100,
    },
    {
        sku: "SPR-BPD-010",
        name: "Bendix Brake Pad DB1369",
        category: "sparepart",
        rating: 5,
        reviews: 19,
        price: 235000,
        originalPrice: 275000,
        badge: "Sale",
        stock: 40,
    },
    {
        sku: "FLT-RAD-011",
        name: "Toyota Coolant Super Long Life",
        category: "filter",
        rating: 4,
        reviews: 8,
        price: 55000,
        originalPrice: null,
        badge: null,
        stock: 90,
    },
    {
        sku: "AKI-GS-012",
        name: "GS Astra NS60LS",
        category: "aki",
        rating: 3,
        reviews: 6,
        price: 650000,
        originalPrice: null,
        badge: "New",
        stock: 25,
    },
] as const;

export async function seedProducts(): Promise<void> {
    const count = await Product.countDocuments();
    if (count > 0) return;

    await Product.insertMany(seedData);
    console.log(`Seeded ${seedData.length} products`);
}
